In [37]:
import pandas as pd, numpy as np, os, fnmatch
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
%config IPCompleter.greedy=True

In [24]:
# File Loading
os.getcwd()
root = "../Data/"
pre_process_Output = "../pre_process/"
pattern = "*.csv"

In [25]:
cols = ['Time', 'avgrss12', 'varrss12', 'avgrss13', 'varrss13', 'avgrss23', 'varrss23']
classes = ['Bending1', 'Bending2', 'Cycling', 'Lying', 'Sitting', 'Standing', 'Walking']
features = ['Time', 'avgrss12', 'varrss12', 'avgrss13', 'varrss13', 'avgrss23', 'varrss23']
target = ['Motion']

In [26]:
pdBending1 = pd.DataFrame({}, columns=cols, dtype=float)
pdBending2 = pd.DataFrame({}, columns=cols, dtype=float)
pdCycling = pd.DataFrame({}, columns=cols, dtype=float)
pdLying = pd.DataFrame({}, columns=cols, dtype=float)
pdSitting = pd.DataFrame({}, columns=cols, dtype=float)
pdStanding = pd.DataFrame({}, columns=cols, dtype=float)
pdWalking = pd.DataFrame({}, columns=cols, dtype=float)

data = pd.DataFrame({}, columns=cols, dtype=float)

In [27]:
def trainingSet(filename, label):
    global pdBending1, pdBending2, pdCycling, pdLying, pdSitting, pdStanding, pdWalking
    temp_df = pd.read_csv(filename, skiprows=5, names=cols, skip_blank_lines=True)
    scaler = MinMaxScaler(feature_range=(0, 1))
    temp = pd.DataFrame(scaler.fit_transform(temp_df), columns=cols)
    if label == 'bending1':
        pdBending1 = pdBending1.append(temp)

    elif label == 'bending2':
        pdBending2 = pdBending2.append(temp)

    elif label == 'cycling':
        pdCycling = pdCycling.append(temp)

    elif label == 'lying':
        pdLying = pdLying.append(temp)

    elif label == 'sitting':
        pdSitting = pdSitting.append(temp)

    elif label == 'standing':
        pdStanding = pdStanding.append(temp)

    elif label == 'walking':
        pdWalking = pdWalking.append(temp)

In [28]:
label = ''
for root, dirs, files in os.walk(root):
    for filename in files:
        if fnmatch.fnmatch(filename, pattern):
            with open(os.path.join(root, filename)) as myfile:
                label = [next(myfile) for x in range(1)][0].split()[2]
            trainingSet((os.path.join(root, filename)), label)

In [29]:
def dataFrameCollector():
    global pdBending1, pdBending2, pdCycling, pdLying, pdSitting, pdStanding, pdWalking, data

    pdBending1['Motion'] = classes[0]
    pdBending2['Motion'] = classes[1]
    pdCycling['Motion'] = classes[2]
    pdLying['Motion'] = classes[3]
    pdSitting['Motion'] = classes[4]
    pdStanding['Motion'] = classes[5]
    pdWalking['Motion'] = classes[6]

    data = data.append(pdBending1.append(pdBending2.append(pdCycling.append(pdLying.append(
        pdSitting.append(pdStanding.append(pdWalking)))))))

dataFrameCollector()

In [30]:
new_index = np.arange(len(data))
data.index = new_index

In [33]:
# Scaling
data[:2]

Motion      Time  avgrss12  avgrss13  avgrss23  varrss12  varrss13  \
0  Bending1  0.000000  0.258065  0.735294  0.590909  0.330769  0.059474   
1  Bending1  0.002088  0.258065  0.745098  0.522727  0.330769  0.000000   

   varrss23  
0  0.677083  
1  0.000000

In [39]:
# Encoding
label_enc = LabelEncoder().fit_transform(data['Motion'])
print(label_enc)

[0 0 0 ... 6 6 6]


In [40]:
# Categorization 
label_categorized = np_utils.to_categorical(label_enc)
print(label_categorized)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
